import type { Lang } from '@/context/lang'

export const content: Record<Lang, {
  nav: Record<string, string>
  hero: Record<string, string>
  labels: Record<string, string>
  routes: Record<string, string>
  bases: Record<string, string>
  itineraries: Record<string, string>
  contact: Record<string, string>
  footer: Record<string, string>
}> = {
  en: {
    nav: {
      routes: 'Routes',
      bases: 'Base Cities',
      gear: 'Gear',
      itineraries: 'Itineraries',
      blog: 'Blog',
      guidedTours: 'Guided Tours',
      travelTips: 'Travel Tips',
      contact: 'Contact',
      planTrip: 'Plan Trip',
      planTripMobile: 'Plan My Trip',
    },
    hero: {
      heading1: 'France has the routes that defined modern climbing.',
      heading2: 'Fontainebleau. Verdon. Céüse.',
      body: 'The most complete climbing country on Earth — bouldering circuits you can reach by train from Paris, multi-pitch limestone gorges, and sport crags where the French grading system was invented.',
      cta: 'Browse all 5 routes',
      secondary: 'Plan a trip',
    },
    labels: {
      difficulty: 'Difficulty',
      style: 'Style',
      pitches: 'Pitches',
      grade: 'Grade',
      approach: 'Approach',
      climbTime: 'Climb time',
      season: 'Best season',
      guided: 'Guided',
      independent: 'Independent',
      viewRoute: 'View route →',
      viewAll: 'View all routes',
      halfDay: 'Half day',
      fullDay: 'Full day',
      multiDay: 'Multi-day',
      region: 'Region',
      baseCity: 'Base city',
      elevation: 'Elevation gain',
      rating: 'Rating',
      reviews: 'reviews',
      totalDay: 'Total Day',
      sponsored: 'Sponsored',
      warnings: 'Warnings',
      gear: 'Gear required',
      gearMinimum: 'Minimum gear',
      crux: 'Crux',
      prerequisites: 'Prerequisites',
      gymDrills: 'Gym preparation',
      testimonials: 'What climbers say',
      nearbyEats: 'Where to eat',
      lodging: 'Where to stay',
      guidePrice: 'Guide price',
      back: '← Back',
      sport: 'Sport',
      trad: 'Trad',
      multiPitch: 'Multi-pitch',
      scramble: 'Scramble',
      quickFacts: 'Quick Facts',
      aboutRoute: 'About This Route',
      guidedOptions: 'Guided Options',
      backToRoutes: '← Back to all routes',
      readyToClimb: 'Ready to climb this?',
      freeAdvice: 'Get Free Trip Advice →',
      noSpam: 'No spam. No sales calls. Just route beta.',
      all: 'All',
      routesAccessible: 'Routes Accessible',
      viewCityGuide: 'View City Guide →',
      driveToClimbs: 'Drive to climbs',
      beforeYouGo: 'Before You Go',
      leadGrade: 'Lead Grade',
      outdoorDays: 'Outdoor Days',
      fitnessLevel: 'Fitness Level',
      skillsToPractice: 'Skills to practise before the trip',
      trainAtGym: 'Train at your gym before you go',
      oneDay: 'One day',
      twoDay: 'Two days',
      threeDay: 'Three days',
    },
    routes: {
      heading: 'All Routes',
      sub: '5 routes across France — from Font sandstone circuits to Verdon multi-pitch and Céüse sport climbing.',
      filterAll: 'All regions',
      filterFont: 'Île-de-France',
      filterVerdon: 'Provence',
      filterCeuse: 'Hautes-Alpes',
      filterCalanques: 'Marseille',
      filterTarn: 'Occitanie',
      noResults: 'No routes match the selected filter.',
    },
    bases: {
      heading: 'Base Cities',
      sub: 'Where to land, sleep, eat, and organize before heading to the rock.',
      restaurants: 'Restaurants',
      lodging: 'Lodging',
      gettingAround: 'Getting around',
      emergency: 'Emergency',
      hospital: 'Hospital',
      routesFrom: 'Routes accessible from here',
    },
    itineraries: {
      heading: 'Trip Itineraries',
      sub: 'Pre-planned climbing trips from half-day to multi-day. Pick your level and go.',
      duration: 'Duration',
      costEstimate: 'Estimated cost',
      bestFor: 'Best for',
      dayBy: 'Day by day',
      morning: 'Morning',
      afternoon: 'Afternoon',
      evening: 'Evening',
      logistics: 'Logistics',
      viewItinerary: 'View itinerary →',
    },
    contact: {
      heading: 'Contact',
      sub: "Questions about a route, guide recommendations, or trip planning? We'll reply within 48 hours.",
      name: 'Name',
      email: 'Email',
      message: 'Message',
      send: 'Send message',
      success: "Message sent — we'll reply within 48 hours.",
      error: 'Something went wrong. Try emailing us directly.',
    },
    footer: {
      tagline: 'The complete climbing guide to France.',
      routes: 'Routes',
      bases: 'Base Cities',
      itineraries: 'Itineraries',
      gear: 'Gear Guide',
      blog: 'Blog',
      contact: 'Contact',
      affiliate: 'Affiliate Disclosure',
      privacy: 'Privacy',
    },
  },
  fr: {
    nav: {
      routes: 'Voies',
      bases: 'Villes de base',
      gear: 'Équipement',
      itineraries: 'Itinéraires',
      blog: 'Blog',
      guidedTours: 'Sorties guidées',
      travelTips: 'Conseils voyage',
      contact: 'Contact',
      planTrip: 'Planifier',
      planTripMobile: 'Planifier mon voyage',
    },
    hero: {
      heading1: 'La France a les voies qui ont défini l\'escalade moderne.',
      heading2: 'Fontainebleau. Verdon. Céüse.',
      body: 'Le pays d\'escalade le plus complet au monde — circuits de blocs accessibles en train depuis Paris, grandes voies en calcaire, et falaises sportives où le système de cotation français a été inventé.',
      cta: 'Voir les 5 voies',
      secondary: 'Planifier un voyage',
    },
    labels: {
      difficulty: 'Difficulté',
      style: 'Style',
      pitches: 'Longueurs',
      grade: 'Cotation',
      approach: 'Approche',
      climbTime: 'Temps d\'escalade',
      season: 'Meilleure saison',
      guided: 'Guidé',
      independent: 'Autonome',
      viewRoute: 'Voir la voie →',
      viewAll: 'Toutes les voies',
      halfDay: 'Demi-journée',
      fullDay: 'Journée',
      multiDay: 'Plusieurs jours',
      region: 'Région',
      baseCity: 'Ville de base',
      elevation: 'Dénivelé',
      rating: 'Note',
      reviews: 'avis',
      totalDay: 'Journée totale',
      sponsored: 'Sponsorisé',
      warnings: 'Avertissements',
      gear: 'Matériel nécessaire',
      gearMinimum: 'Matériel minimum',
      crux: 'Pas clé',
      prerequisites: 'Prérequis',
      gymDrills: 'Préparation en salle',
      testimonials: 'Ce que disent les grimpeurs',
      nearbyEats: 'Où manger',
      lodging: 'Où dormir',
      guidePrice: 'Prix guide',
      back: '← Retour',
      sport: 'Sport',
      trad: 'Trad',
      multiPitch: 'Grande voie',
      scramble: 'Randonnée',
      quickFacts: 'En bref',
      aboutRoute: 'À propos de cette voie',
      guidedOptions: 'Options guidées',
      backToRoutes: '← Toutes les voies',
      readyToClimb: 'Prêt à grimper ?',
      freeAdvice: 'Obtenir des conseils gratuits →',
      noSpam: 'Pas de spam. Juste des infos.',
      all: 'Tous',
      routesAccessible: 'Voies accessibles',
      viewCityGuide: 'Voir le guide ville →',
      driveToClimbs: 'Temps de trajet',
      beforeYouGo: 'Avant de partir',
      leadGrade: 'Cotation en tête',
      outdoorDays: 'Jours en falaise',
      fitnessLevel: 'Niveau physique',
      skillsToPractice: 'Compétences à travailler',
      trainAtGym: 'Entraînement en salle',
      oneDay: 'Un jour',
      twoDay: 'Deux jours',
      threeDay: 'Trois jours',
    },
    routes: {
      heading: 'Toutes les voies',
      sub: '5 voies en France — des circuits de blocs à Font aux grandes voies du Verdon et au sport à Céüse.',
      filterAll: 'Toutes les régions',
      filterFont: 'Île-de-France',
      filterVerdon: 'Provence',
      filterCeuse: 'Hautes-Alpes',
      filterCalanques: 'Marseille',
      filterTarn: 'Occitanie',
      noResults: 'Aucune voie ne correspond au filtre sélectionné.',
    },
    bases: {
      heading: 'Villes de base',
      sub: 'Où atterrir, dormir, manger et s\'organiser avant de partir sur le rocher.',
      restaurants: 'Restaurants',
      lodging: 'Hébergement',
      gettingAround: 'Se déplacer',
      emergency: 'Urgences',
      hospital: 'Hôpital',
      routesFrom: 'Voies accessibles depuis ici',
    },
    itineraries: {
      heading: 'Itinéraires',
      sub: 'Voyages d\'escalade préplanifiés, de la demi-journée à plusieurs jours.',
      duration: 'Durée',
      costEstimate: 'Coût estimé',
      bestFor: 'Idéal pour',
      dayBy: 'Jour par jour',
      morning: 'Matin',
      afternoon: 'Après-midi',
      evening: 'Soir',
      logistics: 'Logistique',
      viewItinerary: 'Voir l\'itinéraire →',
    },
    contact: {
      heading: 'Contact',
      sub: 'Questions sur une voie, conseils de guide ou planification ? Réponse sous 48h.',
      name: 'Nom',
      email: 'Email',
      message: 'Message',
      send: 'Envoyer',
      success: 'Message envoyé — réponse sous 48h.',
      error: 'Une erreur s\'est produite. Essayez de nous écrire directement.',
    },
    footer: {
      tagline: 'Le guide complet de l\'escalade en France.',
      routes: 'Voies',
      bases: 'Villes de base',
      itineraries: 'Itinéraires',
      gear: 'Guide matériel',
      blog: 'Blog',
      contact: 'Contact',
      affiliate: 'Mentions affiliés',
      privacy: 'Confidentialité',
    },
  },
  de: {
    nav: {
      routes: 'Routen',
      bases: 'Basistädte',
      gear: 'Ausrüstung',
      itineraries: 'Reiserouten',
      blog: 'Blog',
      guidedTours: 'Geführte Touren',
      travelTips: 'Reisetipps',
      contact: 'Kontakt',
      planTrip: 'Reise planen',
      planTripMobile: 'Meine Reise planen',
    },
    hero: {
      heading1: 'Frankreich hat die Routen, die das moderne Klettern geprägt haben.',
      heading2: 'Fontainebleau. Verdon. Céüse.',
      body: 'Das vollständigste Kletterland der Welt — Bouldergebiete per Zug aus Paris erreichbar, Mehrseillängen in Kalkschluchten und Sportklettergebiete, wo das französische Bewertungssystem erfunden wurde.',
      cta: 'Alle 5 Routen ansehen',
      secondary: 'Reise planen',
    },
    labels: {
      difficulty: 'Schwierigkeit', style: 'Stil', pitches: 'Längen', grade: 'Grad',
      approach: 'Zustieg', climbTime: 'Kletterzeit', season: 'Beste Saison',
      guided: 'Geführt', independent: 'Eigenständig', viewRoute: 'Route ansehen →',
      viewAll: 'Alle Routen', halfDay: 'Halber Tag', fullDay: 'Ganzer Tag', multiDay: 'Mehrtägig',
      region: 'Region', baseCity: 'Basisstadt', elevation: 'Höhengewinn', rating: 'Bewertung',
      reviews: 'Bewertungen', totalDay: 'Gesamttag', sponsored: 'Gesponsert',
      warnings: 'Warnungen', gear: 'Erforderliche Ausrüstung', gearMinimum: 'Mindestausrüstung',
      crux: 'Schlüsselstelle', prerequisites: 'Voraussetzungen', gymDrills: 'Hallenvorbereitung',
      testimonials: 'Was Kletterer sagen', nearbyEats: 'Essen in der Nähe', lodging: 'Unterkunft',
      guidePrice: 'Führerpreis', back: '← Zurück', sport: 'Sport', trad: 'Trad',
      multiPitch: 'Mehrseillänge', scramble: 'Kraxelei', quickFacts: 'Kurzübersicht',
      aboutRoute: 'Über diese Route', guidedOptions: 'Geführte Optionen',
      backToRoutes: '← Alle Routen', readyToClimb: 'Bereit zum Klettern?',
      freeAdvice: 'Kostenlose Reisetipps →', noSpam: 'Kein Spam. Nur Routenbeta.',
      all: 'Alle', routesAccessible: 'Zugängliche Routen', viewCityGuide: 'Stadtführer ansehen →',
      driveToClimbs: 'Fahrzeit zu Kletterfelsen', beforeYouGo: 'Vor der Abreise',
      leadGrade: 'Vorstiegsgrad', outdoorDays: 'Außentage', fitnessLevel: 'Fitnesslevel',
      skillsToPractice: 'Zu übende Fähigkeiten', trainAtGym: 'Hallentraining',
      oneDay: 'Ein Tag', twoDay: 'Zwei Tage', threeDay: 'Drei Tage',
    },
    routes: {
      heading: 'Alle Routen', sub: '5 Routen in Frankreich — Sandstein-Boulder bis alpine Sportklettergebiete.',
      filterAll: 'Alle Regionen', filterFont: 'Île-de-France', filterVerdon: 'Provence',
      filterCeuse: 'Hautes-Alpes', filterCalanques: 'Marseille', filterTarn: 'Okzitanien',
      noResults: 'Keine Routen entsprechen dem ausgewählten Filter.',
    },
    bases: {
      heading: 'Basistädte', sub: 'Wo man landet, schläft, isst und sich organisiert.',
      restaurants: 'Restaurants', lodging: 'Unterkunft', gettingAround: 'Fortbewegung',
      emergency: 'Notfall', hospital: 'Krankenhaus', routesFrom: 'Erreichbare Routen',
    },
    itineraries: {
      heading: 'Reiserouten', sub: 'Vorgeplante Kletterreisen vom halben Tag bis zu mehreren Wochen.',
      duration: 'Dauer', costEstimate: 'Geschätzte Kosten', bestFor: 'Am besten für',
      dayBy: 'Tag für Tag', morning: 'Morgen', afternoon: 'Nachmittag', evening: 'Abend',
      logistics: 'Logistik', viewItinerary: 'Reiseroute ansehen →',
    },
    contact: {
      heading: 'Kontakt', sub: 'Fragen zu einer Route? Wir antworten innerhalb von 48 Stunden.',
      name: 'Name', email: 'E-Mail', message: 'Nachricht', send: 'Nachricht senden',
      success: 'Nachricht gesendet — Antwort innerhalb von 48 Stunden.',
      error: 'Ein Fehler ist aufgetreten. Schreib uns direkt.',
    },
    footer: {
      tagline: 'Der vollständige Kletterführer für Frankreich.',
      routes: 'Routen', bases: 'Basistädte', itineraries: 'Reiserouten',
      gear: 'Ausrüstungsführer', blog: 'Blog', contact: 'Kontakt',
      affiliate: 'Partneroffenlegung', privacy: 'Datenschutz',
    },
  },
}
